FACEBOOK_APP_ID: '1698356987148102'
FACEBOOK_APP_SECRET: 'ae40c3fb2daa63fcca8e6fec53c821e2'
CLIENT_ID_SECRET_SPOTIFY_APP_B64: 'NTE1MzBhNWFmZDAyNGRiMTg5ZTZhYWVmZjNmMGJhY2Y6MzcxNjk4OGY3Zjg0NDE0MzhlYmNkNGY0OTJmZjE0Y2Q='